name: spygame

services:
  web:
    build: .
    container_name: spygame_app
    restart: unless-stopped
    ports:
      - "${FLASK_PORT:-5000}:5000"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - APPLICATION_PREFIX=/spygame
      # Nota: Usamos el nombre del servicio 'mongodb'
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME:-spygame}:${MONGO_INITDB_ROOT_PASSWORD:-spygame_secret}@mongodb:27017/${MONGO_INITDB_DATABASE:-spygame}?authSource=admin
    networks:
      - spygame-network

  mongodb:
    image: mongo:7.0
    container_name: spygame_db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-spygame}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-spygame}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-spygame_secret}
    volumes:
      - mongodb_data:/data/db
    networks:
      - spygame-network

volumes:
  mongodb_data:

networks:
  spygame-network:
    driver: bridge